#!/bin/bash

EXT=`echo "$1"|awk -F . '{print $NF}'`
NAME=`basename $1 .$EXT`

if [ -z "$2" ]; then
	echo "Usage: $0 <wav-file> <volume>"
	exit 1
fi

echo -n " * Gaining volume with $2..."
mv $1 $NAME-old.$EXT
sox -v $2 $NAME-old.$EXT $1 2> /dev/null
echo -e "OK!"
