#!/bin/bash
#
# Date:    2009-12-16
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Print out some audio info/stats

if [ -z "$1" ]; then
	echo "Usage: $0 <audio-file>"
	exit 1
fi

./require sox

echo -n " * Generating audio statistics for $1..."
sox $1 -n stat
echo -e "OK!"
