#!/bin/bash
#
# Date:    2009-12-16
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Convert the sound from the video to Ogg Vorbis.


EXT=`echo "$1"|awk -F . '{print $NF}'`
BASENAME=`basename $1 .$EXT`

BITRATE="64"

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file> [<audio-quality>]"
	exit 1
fi

./require oggenc || { exit 1; } # vorbis-tools
./audio_extract $1

echo -n " * Converting audio to Ogg Vorbis ($BITRATE kbps)..."

# --downmix
#Downmix stereo to mono. Only allowed on stereo input.
# sjekke om det er stero først? hvis ja, legg på downmix..

if [ "$2" ]; then
	$BITRATE=$2
fi

oggenc "$BASENAME.wav" --downmix -b $BITRATE > "$BASENAME.ogg-compresslog" 2>&1
#	2>&1

echo -e "OK!"
