#!/bin/bash
#
# Date:    2009-12-16
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Convert the video to Ogg Theora.

EXT=`echo "$1"|awk -F . '{print $NF}'`
BASENAME=`basename $1 .$EXT`

VIDEOQUALITY=6 #7
AUDIOQUALITY=4

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file> [<video-quality> <audio-quality>]"
	exit 1
fi

if [ "$3" ]; then
	$VIDEOQUALITY=$2
	$AUDIOQUALITY=$3
fi

# todo: pass på å behold 4:3/16:9 i x:y..

if [ ! -f "$BASENAME.ogv" ] ; then
	echo -n " * Convertering video to Ogg Theora (video quality: $VIDEOQUALITY - audio quality: $AUDIOQUALITY)..."
	ffmpeg2theora $1 -o $BASENAME.ogv \
			--videoquality $VIDEOQUALITY --audioquality $AUDIOQUALITY \
			> "$BASENAME.ogv-compresslog" 2>&1
	#		--width 384 --height 288
	echo -e "OK!"
else
	echo "$BASENAME.ogv allready exist!"
	exit 1
fi
