#!/bin/bash
#
# Date:    2009-12-10
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Convert the video to Ogg Theora.

EXT=`echo "$1"|awk -F . '{print $NF}'`
BASENAME=`basename $1 .$EXT`

WHAT=`./csv $2 $1 what`
DATE=`./csv $2 $1 date`
LOCATION=`./csv $2 $1 location`
TITLE=`./csv $2 $1 title`
NAME=`./csv $2 $1 name`
LICENSE=`./csv $2 $1 license`
ORGANIZATION=`./csv $2 $1 organization`
CONTACT=`./csv $2 $1 contact`

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file> [<csv-file>]"
	exit 1
fi

# todo: pass på å behold 4:3/16:9 i x:y..

if [ ! -f "$BASENAME.ogv" ] ; then
	echo "Generating $BASENAME.ogv"

	if [ $2 ]; then
		ffmpeg2theora $1 -o $BASENAME.ogv \
			--width 384 --height 288 \
			--artist "$NAME" \
			--title "$TITLE" \
			--date "$DATE" \
			--location "$LOCATION" \
			--organization "$ORGANIZATION" \
			--copyright "$COPYRIGHT" \
			--license "$LICENSE" \
			--contact "$CONTACT" \
			> "$BASENAME.ogv-compresslog" 2>&1
	else
		ffmpeg2theora $1 -o $BASENAME.ogv
	#		--width 384 --height 288
	#		> "$BASENAME.ogv-compresslog" 2>&1
	fi
else
	echo "$BASENAME.ogv allready exist!"
	exit 1
fi
