#!/bin/bash
#
# Date:    2009-11-30
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Merge audio stereo track from video

EXT=`echo "$1"|awk -F . '{print $NF}'`
NAME=`basename $1 .$EXT`
AFORMAT=`./audio_format $1`

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file>"
	exit 1
fi

./audio_extract $1
./split_audio $NAME.$AFORMAT
./merge_av $NAME.$AFORMAT $1

rm $NAME.$AFORMAT

#rm $1 $NAME.$AFORMAT $NAME-new.$AFORMAT
#mv $NAME-new.$EXT $1
