#!/bin/bash
# ikke i svn

EXT=`echo "$1"|awk -F . '{print $NF}'`
BASENAME=`basename $1 .$EXT`
COUNT=10

NAME=`./csv $2 $1 name`
LOCATION=`./csv $2 $1 location`

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file> <csv-file>"
	exit 1
fi

./image_text $1 outro-$COUNT black "TAKK TIL"
COUNT=`expr $COUNT + 1`
./image_text $1 outro-$COUNT black "TAKK TIL"
COUNT=`expr $COUNT + 1`
./image_text $1 outro-$COUNT black "TAKK TIL"
COUNT=`expr $COUNT + 1`

./image_text $1 outro-$COUNT black "$NAME" Foredragsholder
COUNT=`expr $COUNT + 1`
./image_text $1 outro-$COUNT black "$LOCATION" Lokaler
COUNT=`expr $COUNT + 1`
		
# takk
# url

./image2video $1 outro
rm $BASENAME-outro*.png
