#!/bin/bash
#
# Date:    2009-12-16
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Generate outro-file with fade in/out from csv-file

EXT=`echo "$1"|awk -F . '{print $NF}'`
BASENAME=`basename $1 .$EXT`
COUNT=10

NAME=`./csv $2 $1 name`
LOCATION=`./csv $2 $1 location`
TAKK=`./csv $2 $1 takk`
URL=`./csv $2 $1 url`

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file> <csv-file>"
	exit 1
fi

echo -n " * Generating outro-video..."

./image_text $1 outro-$COUNT black "TAKK TIL"
./fade $BASENAME-outro-$COUNT.png 3 black
rm $BASENAME-outro-$COUNT.png
COUNT=`expr $COUNT + 1`

./image_text $1 outro-$COUNT black "$NAME" Foredragsholder
./fade $BASENAME-outro-$COUNT.png 1 black
rm $BASENAME-outro-$COUNT.png
COUNT=`expr $COUNT + 1`

./image_text $1 outro-$COUNT black "$LOCATION" Lokaler
./fade $BASENAME-outro-$COUNT.png 1 black
rm $BASENAME-outro-$COUNT.png
COUNT=`expr $COUNT + 1`

# dirty hack
oldIFS=$IFS
IFS='
'
for i in $TAKK ; do
	HVA=`echo "$i" | cut -d ":" -f 1`
	HVEM=`echo "$i" | cut -d ":" -f 2`

	./image_text $1 outro-$COUNT black "$HVEM" "$HVA"
	./fade $BASENAME-outro-$COUNT.png 1 black
	rm $BASENAME-outro-$COUNT.png
	COUNT=`expr $COUNT + 1`
done
IFS=$IFS

for i in $URL ; do
	./image_text $1 outro-$COUNT black " "
	./fade $BASENAME-outro-$COUNT.png 1 black
	rm $BASENAME-outro-$COUNT.png
	COUNT=`expr $COUNT + 1`

	./image_text $1 outro-$COUNT black "$i"
	./fade $BASENAME-outro-$COUNT.png 2 black
	rm $BASENAME-outro-$COUNT.png
	COUNT=`expr $COUNT + 1`
done

./image2video $1 outro
rm $BASENAME-outro*.png

echo -e "OK!"
