#!/bin/bash

EXT=`echo "$1"|awk -F . '{print $NF}'`
NAME=`basename $1 .$EXT`
FORMAT=`./audio_format $1`

if [ -z "$2" ]; then
	echo "Usage: $0 <video-file> <csv-file>"
	exit 1
fi

./check_diskspace $1
./audio_channels_diff $1
./intro $1 $2
./outro $1 $2
./join_video $NAME-new.$FORMAT $NAME-intro$FORMAT $1 $NAME-outro$FORMAT

# todo: bli kvitt mv..
./convert2theora $1 $2
mv $NAME-new.ogv $NAME.ogv
./convert2vorbis $1 $2
mv $NAME-new.ogg $NAME.ogg
