#!/bin/bash

EXT=`echo "$1"|awk -F . '{print $NF}'`
NAME=`basename $1 .$EXT`
FORMAT=`./audio_format $1`

if [ -z "$2" ]; then
	echo "Usage: $0 <video-file> <csv-file>"
	exit 1
fi

echo "Checking diskspace..."
./check_diskspace $1
echo "Checking that both audio channeles is equal..."
#./audio_channels_diff $1
echo "Generating intro..."
#./intro $1 $2
echo "Generating outro..."
#./outro $1 $2
echo "Joining videoes..."
#./join_video $NAME-new.$EXT $NAME-intro.$EXT $1 $NAME-outro.$EXT

#mv $1 $NAME-old.$EXT
#mv $NAME-new.$EXT $1

echo "Converting to theora..."
./convert2theora $1 $2
echo "Converting to vorbis..."
./convert2vorbis $1 $2
