#!/bin/bash
#
# Date:    2009-12-10
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Splits stereo channel into left and right, then
# combines them  back into an audio file (stereo)

BITRATE=`./audio_bitrate $1`
EXT=`echo "$1"|awk -F . '{print $NF}'`
NAME=`basename $1 .$EXT`

if [ -z "$1" ]; then
	echo "Usage: $0 <audio-file>"
	exit 1
fi

./audio_split $1

echo -n " * Merging channels to mono..."
sox -m $NAME-left.wav $NAME-right.wav $NAME-mono.wav 2> /dev/null
echo -e "OK!"

echo -n " * Creating two-channel-stereo from mono..."
sox $NAME-mono.wav -c 2 $NAME-stereo.wav 2> /dev/null
echo -e "OK!"

# stereo filen er allerede ok for dv-lyd!
#echo -n " * Encoding to format: $EXT with bitrate $BITRATE k)..."
#ffmpeg -i $NAME-stereo.wav -acodec $EXT -ab "$BITRATE"k $NAME-new.$EXT 
#2> /dev/null
#echo -e "OK!"

echo -n " * Removing temp. sound files..."
rm $NAME-left.wav $NAME-right.wav $NAME-mono.wav $NAME.wav
mv $NAME-stereo.wav $NAME.wav 
echo -e "OK!"
