#!/bin/bash
FONT="/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf"

if [ $# -gt 2 ]; then
	convert -font $FONT -size 1440x1080 xc:black \
	-fill white -gravity center -pointsize 60 -draw "text 0,0 '${1}'" \
	-fill white -gravity center -pointsize 40 -draw "text 0,60 '${2}'" \
	-append ${3}.png
else
	convert -font $FONT -size 1440x1080 xc:black \
	-fill white -gravity center -pointsize 60 -draw "text 0,0 '${1}'" \
	-append ${2}.png
fi
