#!/bin/bash
#
# Date:    2009-12-04
# Author:  Ole Kristian Lien
# License: GNU General Public License
#
# Show video resolution (x:y)

if [ -z "$1" ]; then
	echo "Usage: $0 <video-file>"
	exit 1
fi

ffmpeg -i $1 2>&1 | grep Video | cut -d "," -f 3 | cut -d " " -f 2
